### ISSUE TITLE
Differences

### ISSUE THREAD

**Issue by MattPotticary** [akdiem/phd_thesis_template#1]
Thanks for this,

Some quick questions:
What are the main differences between this and the ECS thesis?

Also can you change the command names so that this can be a drop in replacement for the ECS thesis template? Currently you have to make a few adjustments to make it compile.

Thanks
Matt (PhD student who is currently writing up)

**Comment by alexdiem** [comment]
Mainly the old ECS thesis template didn't for example accommodate for the Authorship declaration and additional (but nowadays I think essential) lists in the front matter, like the List of Algorithms. It also used the now deprecated subfigure and lstpatch packages.

I'll try to make it backwards compatible, it's a good suggestion, but the original version also used what seems to be an old way of declaring those names, so I'll have to see how successfull I'm going to be with it, but I'll give it a go! 

Really happy to see suggestions come up here!

EDIT: corrected package names of the deprecated packages in the old template.

**Comment by alexdiem** [comment]
Just added a more detailed description of all the changes to the README

**Comment by alexdiem** [comment]
For the command names, I'm going to keep them as they are now as it's more tidy and simpler. However, you should only have to remove the upper case commands to be able to use your tex file with my class. If not, could you post a minimum working example (MWE) that produces the errors you get? Then I can see what else I might need to change to ensure backwards compatibility.

**Comment by alexdiem** [comment]
Closed issue due to inactivity
