### ISSUE TITLE
How did you set the margins for even and odd pages

### ISSUE THREAD

**Issue by Kevinpsk** [akdiem/phd_thesis_template#4]
HI there, 

I am also a PhD student in Southampton and I am using your template to write my thesis now. It is a very good tool. But I was just wondering how did you set different margins for even and odd pages? I saw the following command in your phdclass.cls file,

`\setmarginsrb           { 1.5in}  % left margin
                        { 0.6in}  % top margin
                        { 1.0in}  % right margin
                        { 0.8in}  % bottom margin
                        {  20pt}  % head height
                        {0.25in}  % head sep
                        {   9pt}  % foot height
                        { 0.3in}  % foot sep
`

I guess this is how margins are set, but how does the document figure out how to apply them in odd and even pages? 

I want to ask this because I am trying add a PDF document as an appendix in the end of my thesis. I used the pdfpages package and added the PDF file using 

`\includepdf[pages=-]{file.pdf}`

But the layout of this PDF file in my thesis is a mess, see the pic below. 

![screenshot from 2017-08-13 16-37-43](https://user-images.githubusercontent.com/9253234/29251085-feab7346-8046-11e7-9d0a-545f0780e292.png)

I have searched about this for the pdfpages package, but none of the solutions I found is working. I am thinking if I can solve this by restting the margin values for these pages separately. So do you think this is a good way in solving this? 

Cheers,
Shuokai

**Comment by alexdiem** [comment]
Hi, if all you want to do is append your existing pdf files I'd recommend using a tool such as pdftk to combine the pdfs:

`pdftk in1.pdf in2.pdf cat output out1.pdf`

The books class which the template is based on automatically activates the twopages option, which tells Latex that left and right margins are different on even and odd pages.

**Comment by Kevinpsk** [comment]
HI, Thanks for your reply. I have solved this problem by setting the offset argument of the pdfpages package. But I have to do this for each page, which is a bit annoying but bearable. I guess you method could work as well, although I am not sure how do it in Windows. Your command is to be used in Linux right? Can I also using in windows command line? Haven't tried this way before.

**Comment by alexdiem** [comment]
I'm afraid I can't help with Windows as I haven't used it in almost 10 years. You just need any software that can combine pdf files into one, I'm sure there must be one for Windows. Maybe even pdftk has a Windows version, but I don't know that.
